spring.application.name=user-service

# Supabase PostgreSQL Connection
spring.datasource.url=jdbc:postgresql://aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.hwzcsgsjqftamjxvtbrf
spring.datasource.password=IUsXyDCd2MqPChPG
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
# Disable prepared statements - required for Supabase transaction-mode pooler (port 6543)
spring.datasource.hikari.connection-init-sql=select 1
spring.jpa.properties.hibernate.jdbc.use_streams_for_binary=false
